---
- name: "Create user dot files"
  file: src={{ dotfiles_from_repo }}/{{ item }} dest={{ ansible_env.HOME }}/{{ item }} state=link
  with_items:
    - ".tmux.conf"
    - ".gitignore_global"

- name: "Configure git global ignore file"
  git_config:
    scope: global
    name: core.excludesfile
    value: "{{ ansible_env.HOME }}/.gitignore_global"
