---

- name: Create code directory
  file: path={{ code_directory }} state=directory

- name: "Clone provision-dev-host"
  git:
    repo: https://github.com/roadr/provision-dev-host.git
    dest: "{{ code_directory }}/provision-dev-host"
    update: no

- name: "Fix remote git uri used for provision-dev-host repo"
  replace:
    dest: "{{ code_directory }}/provision-dev-host/.git/config"
    regexp: https.+git
    replace: "git@github.com:roadr/provision-dev-host.git"
    backup: yes
