---

- name: "Check versions available"
  uri:
    url: "{{ build_url }}"
    return_content: yes
  register: server_response
  tags: intellij

- set_fact:
    build: "{{ server_response['json']['IIC'][0]['build'] }}"
    date: "{{ server_response['json']['IIC'][0]['date'] }}"
    link: "{{ server_response['json']['IIC'][0]['downloads']['linux']['link'] }}"
  tags: intellij

- set_fact:
    build_dir: "{{ build }}-{{ date }}"
  tags: intellij

- file:
    state: directory
    path: /opt/intellij/{{ build_dir }}
  become: true
  tags: intellij
  register: existing_installation

- name: "Download intellij"
  become: true
  unarchive:
    extra_opts: ['--strip-components=1', '--show-stored-names']
    src: "{{ link }}"
    dest: /opt/intellij/{{ build_dir }}
    creates: yes
    copy: no
  tags: intellij
  when: existing_installation | changed

- name: "Setup links"
  become: true
  file:
    state: link
    src: /opt/intellij/{{ build_dir }}
    path: /opt/intellij/current
  tags: intellij

- name: "Configure desktop shortcut"
  become: true
  template:
    src: intellij.desktop.j2
    dest: /usr/share/applications/intellij.desktop
    mode: 0644
  tags: intellij

