---

- name: "Check versions available"
  uri:
    url: "{{ build_url }}"
    return_content: yes
  register: server_response
  tags: intellij

- set_fact:
    build: "{{ server_response['json']['IIU'][0]['build'] }}"
    date: "{{ server_response['json']['IIU'][0]['date'] }}"
    link: "{{ server_response['json']['IIU'][0]['downloads']['linux']['link'] }}"
  tags: intellij

- set_fact:
    build_dir: "{{ build }}-{{ date }}"
  tags: intellij

- file:
    state: directory
    path: /opt/intellij/{{ build_dir }}
  become: true
  tags: intellij
  register: existing_installation

- name: "Download intellij"
  become: true
  unarchive:
    extra_opts: ['--strip-components=1', '--show-stored-names']
    src: "{{ link }}"
    dest: /opt/intellij/{{ build_dir }}
    copy: no
  tags: intellij
  when: existing_installation | changed or
          force_intellij is defined and force_intellij

- name: "Setup links"
  become: true
  file:
    state: link
    src: /opt/intellij/{{ build_dir }}
    path: /opt/intellij/current
  tags: intellij

- name: "Configure desktop shortcut"
  become: true
  copy:
    src: intellij.desktop
    dest: /usr/share/applications/intellij.desktop
    mode: 0644
  tags: intellij

- name: "Setup idea vm options"
  become: true
  copy:
    src: idea64.vmoptions
    dest: /opt/intellij/current/bin
    mode: 0644
  tags: intellij

