---
- name: Verify installed java versions
  file: path=/usr/java/jdk{{ item.installed_version }} state=directory
  become: True
  with_items: "{{ java_versions }}"
  register: verify_installation_directories

- name: Download jdk
  uri: 
    url:
      "http://download.oracle.com/otn-pub/java/jdk/{{ item.package_version }}-{{ item.build }}/jdk-{{ item.package_version }}-linux-x64.rpm"
    HEADER_Cookie:
      "gp gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
    dest: "/tmp/ansible_java_{{ item.package_version }}.rpm"
    status_code: 200,304
  with_items: "{{ java_versions }}"
  notify: 
    - "Remove downloaded java rpms"
  when:
    - force_java_installation or verify_installation_directories | changed

- name: Install jdk
  dnf: name=/tmp/ansible_java_{{ item.package_version }}.rpm state=present
  become: true
  with_items: "{{ java_versions }}"
  when:
    - force_java_installation or verify_installation_directories | changed

- name: Configure jre alternatives
  alternatives:
    name: "{{ item[1] }}"
    path: "/usr/java/jdk{{ item[0].installed_version }}/jre/bin/{{ item[1] }}"
    link: "/usr/bin/{{ item[1] }}"
  become: true
  with_nested: 
    - "{{ java_versions }}"
    - ['java']
  when:
    - force_java_installation or verify_installation_directories | changed

- name: Configure jdk alternatives
  alternatives:
    name: "{{ item[1] }}"
    path: "/usr/java/jdk{{ item[0].installed_version }}/bin/{{ item[1] }}"
    link: "/usr/bin/{{ item[1] }}"
  become: true
  with_nested: 
    - "{{ java_versions }}"
    - ['javac']
  when:
    - force_java_installation or verify_installation_directories | changed
