---
- name: Retrieve jdk rpm urls
  java_rpm_util:
    java_versions: "{{ j_versions }}"
  register: recent_java_info
  tags: java

- name: Verify installed java versions
  file: path=/usr/java/{{ item[1].complete_version }} state=directory
  become: True
  with_nested:
    - "{{ j_versions }}"
    - "{{ recent_java_info.meta }}"
  register: verify_installation_directories
  tags: java

- name: Download jdk rpm
  uri:
     url: "{{item.rpm_url}}"
     headers:
        Cookie: "gp gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
     dest: "/tmp/ansible_java_{{item.major_version}}.rpm"
     status_code: 200, 304
  with_items: "{{ recent_java_info.meta }}"
  when:
    - force_java_installation or verify_installation_directories is changed
  tags: java

- name: Install jdk
  dnf: name=/tmp/ansible_java_{{ item }}.rpm state=present
  become: true
  with_items: "{{ j_versions }}"
  when:
    - force_java_installation or verify_installation_directories is changed
  tags: java

- name: Configure jdk and jre alternatives
  alternatives:
    name: "{{ item[1] }}"
    path: "/usr/java/{{ item[0].complete_version }}/bin/{{ item[1] }}"
    link: "/usr/bin/{{ item[1] }}"
    priority: "{{ j_priorities[item[0].major_version] }}"
  become: true
  with_nested: 
    - "{{ recent_java_info.meta }}"
    - ['javac', 'java']
  tags: java

- name: Java home environment variable
  lineinfile:
    dest: /etc/profile.d/java.sh
    state: present
    create: yes
    backup: yes
    line: export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s|bin/javac||")
  become: true
  tags: java
