- git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
    update: yes
  tags: pyenv

- git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: ~/.pyenv/plugins/pyenv-virtualenv
    update: yes
  tags: pyenv

- blockinfile:
    dest: ~/.bashrc
    block: |
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        if command -v pyenv 1>/dev/null 2>&1; then
            eval "$(pyenv init -)"
        fi
        eval "$(pyenv virtualenv-init -)"
  tags: pyenv

