---
- name: Enable nvim repo
  become: true
  command: dnf -y copr enable dperson/neovim

- name: Install nvim
  become: true
  dnf: name=neovim enablerepo='dperson/neovim' state=present

- name: Vim alias for nvim
  lineinfile:
    dest: /etc/profile.d/vim.sh
    state: present
    create: yes
    backup: yes
    line: alias vim='nvim'
  become: true

- name: "Create nvim config dir"
  file:
   path: "{{ ansible_env.HOME }}/.config/nvim"
   state: directory

- name: "Link default nvim configuration file"
  file:
    src: "{{ ansible_env.HOME }}/code/provision-dev-host/roles/nvim/files/.vimrc"
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    state: link

- name: "Create autoload directory"
  file:
    path: "{{ ansible_env.HOME }}/.config/autoload"
    state: directory

- name: "Setup vim plug"
  uri:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.config/nvim/autoload/"
