---
- name: Enable nvim repo
  become: true
  command: dnf -y copr enable dperson/neovim

- name: Install nvim
  become: true
  dnf: name=neovim enablerepo='dperson/neovim' state=present

- name: Vim alias for nvim
  lineinfile:
    dest: /etc/profile.d/vim.sh
    state: present
    create: yes
    backup: yes
    line: alias vim='nvim'
  become: true
